export const cardData = [
  { title: "ChatGPT", image: "chatgpt.jpeg", message: "I want to buy ChatGPT tool" },
  { title: "Jenni.ai", image: "jenni.jpeg", message: "I want to buy Jenni.ai tool" },
  { title: "Scite.ai", image: "scite.jpeg", message: "I want to buy Scite.ai tool" },
  { title: "Stealthwriter.ai", image: "stealthwriter.png", message: "I want to buy Stealthwriter.ai tool" },
  { title: "Writehuman.ai", image: "writehuman.jpeg", message: "I want to buy Writehuman.ai tool" },
  { title: "Hix.ai Bypass", image: "hix.jpeg", message: "I want to buy Hix.ai Bypass tool" },
  { title: "BypassGPT.ai", image: "bypassgpt.jpeg", message: "I want to buy BypassGPT.ai tool" },
  { title: "Canva", image: "canva.png", message: "I want to buy Canva tool" },
  { title: "LinkedIn Premium", image: "linkedin.jpeg", message: "I want to buy LinkedIn Premium tool" },
  { title: "Coursera Plus", image: "coursera.jpeg", message: "I want to buy Coursera Plus tool" },
  { title: "CourseHero", image: "coursehero.png", message: "I want to buy CourseHero tool" },
  { title: "Chegg", image: "chegg.jpeg", message: "I want to buy Chegg tool" },
  { title: "Turnitin Student", image: "turnitin_student.jpeg", message: "I want to buy Turnitin Student tool" },
  { title: "Turnitin Instructor", image: "turnitin_instructor.jpeg", message: "I want to buy Turnitin Instructor tool" },
  { title: "Originality", image: "originality.png", message: "I want to buy Originality tool" },
  { title: "Quillbot", image: "quillbot.jpeg", message: "I want to buy Quillbot tool" },
  { title: "Grammarly", image: "grammarly.jpeg", message: "I want to buy Grammarly tool" },
  { title: "Midjourney", image: "midjourney.jpeg", message: "I want to buy Midjourney tool" },
  { title: "Leonard.ai", image: "leonard.jpeg", message: "I want to buy Leonard.ai tool" },
  { title: "Freepik", image: "freepik.jpeg", message: "I want to buy Freepik tool" },
  { title: "Envato Elements", image: "envato.png", message: "I want to buy Envato Elements tool" },
  { title: "Semrush", image: "semrush.png", message: "I want to buy Semrush tool" },
  { title: "ElevenLabs", image: "elevenlabs.png", message: "I want to buy ElevenLabs tool" },
  { title: "Runway ML", image: "runwayml.jpeg", message: "I want to buy Runway ML tool" },
  { title: "Hailou.ai", image: "hailou.jpeg", message: "I want to buy Hailou.ai tool" },
  { title: "VideoExpress.ai", image: "videoexpress.png", message: "I want to buy VideoExpress.ai tool" },
  { title: "Office 365", image: "office365.png", message: "I want to buy Office 365 tool" },
  { title: "VidIQ", image: "vidiq.png", message: "I want to buy VidIQ tool" },
  { title: "Wordtune", image: "wordtune.png", message: "I want to buy Wordtune tool" },
];
