export const vpsPlans = [
    {
      title: "USA Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "usa-flag.png",
      message: "I want to buy USA Private VPS",
    },
    {
      title: "UK Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "uk-flag.png",
      message: "I want to buy UK Private VPS",
    },
    {
      title: "Australia Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "australia-flag.png",
      message: "I want to buy Australia Private VPS",
    },
    {
      title: "Netherlands Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "netherlands-flag.png",
      message: "I want to buy Netherlands Private VPS",
    },
    {
      title: "Japan Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "japan-flag.png",
      message: "I want to buy Japan Private VPS",
    },
    {
      title: "Singapore Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "singapore-flag.png",
      message: "I want to buy Singapore Private VPS",
    },
    {
      title: "China Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "china-flag.png",
      message: "I want to buy China Private VPS",
    },
    {
      title: "Canada Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "canada-flag.png",
      message: "I want to buy Canada Private VPS",
    },
    {
      title: "Switzerland Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "switzerland-flag.png",
      message: "I want to buy Switzerland Private VPS",
    },
    {
      title: "Germany Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "germany-flag.png",
      message: "I want to buy Germany Private VPS",
    },
    {
      title: "France Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "france-flag.png",
      message: "I want to buy France Private VPS",
    },
    {
      title: "Spain Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "spain-flag.png",
      message: "I want to buy Spain Private VPS",
    }
  ];