export const vpsPlans = [
    {
      title: "USA Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "usa.png",
      message: "I want to buy USA Private VPS",
    },
    {
      title: "UK Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "uk.png",
      message: "I want to buy UK Private VPS",
    },
    {
      title: "Australia Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "australia.png",
      message: "I want to buy Australia Private VPS",
    },
    {
      title: "Netherlands Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "netherlands.png",
      message: "I want to buy Netherlands Private VPS",
    },
    {
      title: "Japan Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "japan.png",
      message: "I want to buy Japan Private VPS",
    },
    {
      title: "Singapore Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "singapore.png",
      message: "I want to buy Singapore Private VPS",
    },
    {
      title: "China Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "china.png",
      message: "I want to buy China Private VPS",
    },
    {
      title: "Canada Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "canada.png",
      message: "I want to buy Canada Private VPS",
    },
    {
      title: "Switzerland Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "switzerland.png",
      message: "I want to buy Switzerland Private VPS",
    },
    {
      title: "Germany Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "germany.png",
      message: "I want to buy Germany Private VPS",
    },
    {
      title: "France Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "france.png",
      message: "I want to buy France Private VPS",
    },
    {
      title: "Spain Private VPS",
      price: "Custom Pricing",
      features: ["Admin Access", "Secure & Reliable", "High-Speed Performance"],
      image: "spain.png",
      message: "I want to buy Spain Private VPS",
    }
  ];